### PR TITLE
Add Mutual NDA and supporting files

### PR DESCRIPTION
**Pull request by anseljh**
@kemitchell, this is my first time writing these schema and signatures files, so a quick eyeball would be appreciated.

### CODE REVIEW

**Comment by kemitchell** [comment]
The break is my fault. I'll fix it, but will probably involve some rebasing.

**Comment by anseljh** [comment]
Well, that was messy, but I think it ended up in the right place. Clearly, my git-fu still needs improvement.

**Comment by kemitchell** [comment]
The messiness was not your fault. It was mine.

There was a test-break on the master branch that shouldn't have been there. When I saw your fail tests, I finally saw that break, which had nothing to do with your changes. When I cleaned up master, it broke fast forward for your changes.

**Comment by anseljh** [comment]
@kemitchell OK to merge?

**Comment by kemitchell** [comment]
Fire away.

**Comment by anseljh** [comment]
Seems I don't have permission.

**Comment by kemitchell** [comment]
Should now.

**Pull request merged**
